CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE GRID_CELL (
    ID BIGSERIAL NOT NULL,
    SHAPE integer NOT NULL,
    LEVEL integer NOT NULL,
    GEOM geometry(Geometry,4326) NOT NULL,
    PROJ integer NOT NULL,
    HASH integer NOT NULL UNIQUE,
    INFO jsonb,
    CONSTRAINT PK_GRID_CELL PRIMARY KEY (ID)
);





CREATE INDEX IDX_GRID_CELL_GEOM ON GRID_CELL USING GIST(GEOM);
